name: Cypress Accessibility Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  cypress-test-accessibility:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes Cypress
        run: npm run test 

      - name: Gerar relatório HTML 
        run: npm run report

      - name: Upload do relatório HTML
        uses: actions/upload-artifact@v4
        with:
          name: a11y-html-report
          path: cypress/reports/html/report-test-accessibility-index.html
