name: Cypress Accessibility Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  cypress-test-accessibility:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Run Cypress tests
        run: npm run test || echo "Tests failed but continuing"

      - name: Merge reports
        run: npm run report:merge || echo "Merge failed but continuing"

      - name: Generate report
        run: npm run report:generate || echo "Report generation failed but continuing"

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: a11y-html-report
          path: cypress/reports/html/report-test-accessibility-index.html