name: Cypress Accessibility Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  cypress-test-accessibility:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Run Cypress tests
        run: npm run test || echo "Tests failed but continuing"

      - name: Verificar se há JSONs válidos para mesclar
        id: check-reports
        run: |
          valid=$(grep -l '"stats"' cypress/reports/json/*.json 2>/dev/null | wc -l)
          echo "Found $valid valid report(s)"
          if [ "$valid" -gt 0 ]; then
            echo "has_reports=true" >> $GITHUB_OUTPUT
          else
            echo "has_reports=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Merge reports
        if: steps.check-reports.outputs.has_reports == 'true'
        run: npm run report:merge

      - name: Generate report
        if: steps.check-reports.outputs.has_reports == 'true'
        run: npm run report:generate

      - name: Upload HTML Report
        if: steps.check-reports.outputs.has_reports == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: a11y-html-report
          path: cypress/reports/html/report-test-accessibility-index.html
